### ISSUE TITLE
Tabs in the source questions.txt

### ISSUE THREAD

**Issue by noah-cheesman** [oscarbenjamin/txt2bb#6]
@liamwheen 

I have been using tabs in the the source questions.txt for the sake of readability (especially when using the genius %{}% method ). However, I have just realised after looking at the blackboard format questions_bb.txt. that this will be a problem. Can we preprocess the questions.txt to strip out tabs (they serve no purpose right?), or is there an alternative already?

Noah

**Comment by liamwheen** [comment]
@noah-cheesman thanks for pointing this out, my text editor turns tabs into spaces so it never occured to me. All fixed now, cheers

**Comment by oscarbenjamin** [comment]
You should reference the PR i.e. #7
